language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sumitaec108/insta-clone -f Dockerfile.dev .
script:
  - docker run -e CI=true sumitaec108/insta-clone npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "instaclone-react"
  env: "Instaclonereact-env"
  bucket_name: "elasticbeanstalk-us-east-2-906283353384"
  bucket_path: "instaclone-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY