version: '3'
services: 
    node-application:
        environment:
            - CHOKIDAR_USEPOLLING=true
        build:
            context: .
        ports:
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
    tests:
        build:
            context: .
        volumes: 
                - /app/node_modules
                - .:/app
        command: ["npm", "run", "test"]